apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-manual-test
  name: nginx-manual-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-manual-test
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-manual-test
    spec:
      containers:
        - image: registry.prolion.com/bitnami/nginx:1.27.3
          name: nginx
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: nginx-config
              mountPath: /opt/bitnami/nginx/conf/server_blocks/
            - name: nginx-auth
              subPath: .htpasswd
              mountPath: /opt/bitnami/nginx/conf/auth/.htpasswd
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: nginx-auth
          secret:
            secretName: nginx-auth

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-manual-test
  name: nginx-manual-test
spec:
  ports:
    - name: 80-8080
      port: 80
      targetPort: 8080
  selector:
    app: nginx-manual-test
  type: LoadBalancer
---
apiVersion: v1
data:
  default.conf: |+
    server {
      listen 8080;
      location / {
        default_type text/plain;
        return 200 'Running in Kubernetes via ConfigMap!';
      }
      location /secret {
        auth_basic "Restricted";
        auth_basic_user_file /opt/bitnami/nginx/conf/auth/.htpasswd;
      }
    }

kind: ConfigMap
metadata:
  name: nginx-config
---
apiVersion: v1
data:
  .htpasswd: bmdpbnhfdXNlcjokYXByMSRwVHBnWVl1QSRRS2dlM3FtUU9USzZZVTJqN2xDemMvCg==
kind: Secret
metadata:
  name: nginx-auth
  namespace: default
